[member]
name = "test"
public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGy+OD4AR5a8OhKDnP8u5zQebzlPR
CaJtSgD2ItN18RGWYf+so3LcjJTSHrKsk5gjp68wJjKoq2CTGOcb7OgwcQ==
-----END PUBLIC KEY-----
"""
joined_epoch = 1
added_by = "376c113f45c3"
